### ISSUE TITLE
Lack of knowledge of TextFeatureSelection method

### ISSUE THREAD

**Issue by heriistantoo** [StatguyUser/TextFeatureSelection#19]
Thanks for the amazing work. I tried the TextFeatureSelection method, but in the end, I have =-inf or #NAME? results. Could you please explain to me why this is happening? or how can i fix it?

![image](https://user-images.githubusercontent.com/17525413/218342974-5618b845-c276-4efa-8e7a-a9cb578dc2d9.PNG)

**Comment by StatguyUser** [comment]
-inf is the correct output. Mathematically speaking, it is possible to get -inf results as a result of the formulas used for calculating feature selection scores. for "#NAME?", it is related to Microsoft excel.
